name = input (" name :")
age = input ("age :")
height = input ("height :")
print (name , type (name))
print (age, type (age))
print (height, type (height))
age = int(age)
print(age , type(age))
height = float(height,type (height))